# Podfile

# This tells CocoaPods we want to target iOS versions 8.0 and above.
platform :ios, '8.0'

# Instruct CocoaPods to use dynamic frameworks instead of static libraries for Pods

use_frameworks! 

target ‘Tweeter’ do
	pod ‘AFNetworking’, ‘3.0.0’
	pod ‘BDBOAuth1Manager’, ‘2.0.0’
end
